<style>
    /* #### Generated By: http://www.cufonfonts.com #### */

    @import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap');

    * {
        font-family: 'Open Sans', sans-serif !important;

    }

    .grid {
        width: 100%;
        margin-left: auto;
        margin-right: auto;
    }

    .grid div {
        width: 100%;
    }

    h1.logo-text {
        font-size: 20px;
        line-height: 0;
        color: #151515;
    }

    p.logo-slogon {
        font-size: 15px;
        font-weight: 300;
        /* margin-top: -15px;*/
    }

    h1.head-text {
        font-size: 14px;
        font-weight: 300;
        line-height: 0;
    }

    body {
        width: 100%;
        text-align: left;

    }

    html {
        margin: 0;
        padding: 0;
    }

    table {
        text-align: left;

    }

    td,
    th {
        /*border: 1px solid #dddddd;*/
        text-align: left;
        padding: 8px;
    }

    .border-orange {
        background-color: {{$brandcolor }};
        text-align: right;
        color: white;
        height: 10px !important;
        padding: 0 !important;
        margin-top: -50px;
        width: 100%;
    }

    .og-text {
        /*position: absolute;*/
        color: {{$brandcolor }};
        background-color: white;
        margin-right: 15%;
        font-size: 50px;
        width: 100%;
        max-width: 270px;
        font-weight: 600;
        text-align: center;
        margin-left: auto;
        margin-bottom: 0;
        height: 80px;
        line-height: 0.9;
        padding: 0px !important;
    }

    .remarqe {
        width: 100%;
        background-color: #ff2e2e;
        padding: 0;
        margin: 0;
        height: 30px;
        text-align: center;
        color: white;
    }

    .icon-text img {
        width: 15px !important;
        height: 15px !important;
        vertical-align: middle;
        margin-right: 5px;
    }

    .content-right-td {
        text-align: left;
        display: block;
        margin-left: 25%;
    }

    .margin-left {
        margin-right: -50px;
    }

    .icon-text {
        background-color: {{$brandcolor }};
        width: 15px;
        height: 15px;
        padding: 8px;
        border-radius: 100% !important;
        margin-right: 10px;

    }

    .devis-table {
        border-collapse: collapse;

    }

    .devis-table td,
    .devis-table th {
        padding: 8px;
        border: none;
    }

    .devis-table tr {
        background-color: #e7e7e7;
    }

    .devis-table tr:nth-child(even) {
        background-color: #ffffff;
    }


    .devis-table th {
        padding-top: 5px;
        padding-bottom: 5px;
        text-align: left;
        background-color: {{$brandcolor }};
        color: white;
    }

    .total-border {}

    h1.head-text.sb-total {
        color: #2f2f2f;
        margin-left: 33px;
    }

    .total-border {
        width: 100%;
        background-color: {{$brandcolor }};
        color: white;
        margin-right: 2px;
        padding-left: 40px;
        padding-right: 40px;
        height: 40px;
    }

    span.px-stl {
        margin-right: -40px;
        margin-left: 40px;
    }

    .wd-90 {
        margin: 20px;
    }

    .wd-90.margin-top {
        margin-top: 30px;
        margin-bottom: -40px;
    }

    .border-info {
        width: 100%;
        height: 15px;
        overflow: visible;
        background-color: {{$brandcolor }};
        margin: 0;
        margin-top: 2px;
        padding: 0;
    }

    .border-info span {
        color: {{$brandcolor }};
        width: 100%;
        max-width: 150px;
        background-color: white;
        margin-left: 70%;
        display: block;
        text-align: center;
        line-height: 0.8;
    }

    footer {
        position: fixed;
        bottom: -60px;
        left: 0px;
        right: 0px;
        height: 50px;

        /** Extra personal styles **/
        background-color: #03a9f4;
        color: white;
        text-align: center;
        line-height: 35px;
    }
.footer{
    position: fixed;
    bottom: 9%;
}
.logo-pdf{
    max-width: 180px;
    max-height: 150px;
    display: block;
}
</style>
<?php
//$url = asset('image')
$phonepng = file_get_contents('image/icon/phone.png');
$phonepng64 = base64_encode($phonepng);
$test = '454564df';
?>
<head>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&display=swap" rel="stylesheet">
    <title>DESKY - DEVIS N° {{ $OID }}</title>
</head>
<footer>
    Copyright &copy; <?php echo date("Y");?>
</footer>
<div style="width: 100%;">
    <div class="wd-90 margin-top">

        <table style="width:100%; height: 100px; padding: 0; margin: 0;" dir="ltr" align="left">
            <tr>
                <th style="">
                    <div>
                       @if($logo != "" && $logo != null)
                       <img src="http://{{ env('APP_URL') }}/{{ $logo }}" class="logo-pdf">

                       @else
                        <h1 class="logo-text"> {{ Auth::user()->fname }} {{ Auth::user()->lname }}</h1>
                        <p class="logo-slogon"> {{ $slogon }} </p>
                       @endif

                    </div>
                </th>
                <th style="text-align: right;">
                    <div class="content-right-td">
                        <h1 class="head-text"> Date de la Creation</h1>
                        <p class="slogon-text" style="font-weight: 300;"> {{ date("d/m/Y", strtotime($created_at)) }} </p>
                    </div>
                </th>
            </tr>
            <tr>
                <td colspan="2"><br></td>
            </tr>

        </table>
    </div>

    <table style="width:100%; height: 100px; padding: 0; margin: 0">
        <tr>
            <th> </th>
            <th> </th>
        </tr>
        <tr style=" padding: 0; margin: 0;">
            <td colspan="2" class="border-orange">
                <div class="og-text"><span class=""> FACTURE </span></div>
            </td>
        </tr>
    </table>
    <div class="wd-90">

        <!-- Infos Devis Section -->
        <table style="width:100%; height: 100px; padding: 0; margin: 0;" dir="ltr" align="left">
            <tr>

                <th style="text-align: left;">
                    <div class="">
                        <h1 class="head-text" style="font-weight: 400; font-size: 18px;"> Contactez-nous
                        </h1>
                        <br>
                        @if($telephone != "" && $telephone != null)
                        <div class="head-text" style="font-weight: 400; width: 100%;">
                            <div class="icon-text" style="float: left;">
                                <img src='http://{{ env('APP_URL') }}/image/icon/phone.png'>
                            </div>
                            <div style="font-size: 14px;font-weight: 400;">{{ $telephone }} </div>
                        </div>
                        <br>
                        @endif
                        <div class="head-text" style="font-weight: 400;">
                            <div class="icon-text" style="float: left">
                                <img src='http://{{ env('APP_URL') }}/image/icon/email.png'>
                            </div>
                            <div style="font-size: 14px;font-weight: 400;">{{ $b_email }}</div>
                        </div>
                        <br>
                        @if($siteweb != "")
                        <div class="head-text" style="font-weight: 400;">
                            <div class="icon-text" style="float: left">
                                <img src='http://{{ env('APP_URL') }}/image/icon/global.png'>
                            </div>
                            <div style="font-size: 14px;font-weight: 400;">{{ $siteweb }}</div>
                        </div>
                        @endif
                        <br>
                        <h1 class="head-text" style="font-weight: 400;">statut: <span class="status">en attente de paiement</span></h1>
                        <br>
                        <h1 class="head-text" style="font-weight: 400;">méthode de paiement: <span class="status">Cash</span></h1>

                    </div>
                </th>
                <th style="text-align: left; margin-left: 20px;">
                    <div class=" margin-left">
                        <h1 class="head-text" style="font-weight: 600; font-size: 20px;"> N° {{ $OID }}
                        </h1>
                        <br>

                        <h1 class="head-text" style="font-weight: 400; font-size: 18px;"> Client
                        </h1>
                        <br>
                        <h1 class="head-text" style="font-weight: 400;"> Numéro de client: {{ $CID }}
                        </h1>
                        <br>
                        <h1 class="head-text" style="font-weight: 400;"> {{ $c_name }}
                        </h1>
                        <br>
                        <h1 class="head-text" style="font-weight: 400;"> {{ $c_email }}
                        </h1>
                        <br>
                        <h1 class="head-text" style="font-weight: 400;"> {{ $c_phone }}</h1>

                    </div>
                </th>
            </tr>
        </table>
        <br>
        <br>

        <!-- devis detils section -->

        <table
            style="width:100%; min-height: 1000px; padding: 0; margin: 0;border-bottom: solid 1px #e7e7e7;    border-left: solid 1px #e7e7e7;    border-right: solid 1px #e7e7e7;"
            class="devis-table" dir="ltr">
            <tr>
                <th style="text-align: center">N°</th>
                <th>Désignation</th>
                <th style="text-align: center">Prix</th>
                <th style="text-align: center">Quantité</th>
                <th style="text-align: center">Total</th>
            </tr>
@php $i=1 @endphp
@foreach($items as $item)
                <tr>
                    <td style="text-align: center">{{ $i++ }}</td>

                    <td style="font-size: 80%">{{ $item->article }}</td>
                    <td style="text-align: center; font-size: 85%">{{  number_format($item->price, 2, '.', ',') }} MAD</td>
                    <td style="text-align: center; font-size: 85%">{{ $item->quantity }}</td>
                    <td style="text-align: center; font-size: 85%">{{ number_format(($item->price*$item->quantity), 2, '.', ',') }}</td>
                </tr>
@endforeach
        </table>
        <br>
        <br>
        <!-- Section information generale -->
        <table style="width:100%; height: 100px; padding: 0; margin: 0;" dir="ltr" align="left">
            <tr>
                <th style="text-align: left;">
                    <div class=" ">

                        <br>

                        <h1 class="head-text" style="font-weight: 400; font-size: 18px;"> Informations de paiement
                        </h1>
                        <br>
                        <br>
                        <h1 class="head-text" style="font-weight: 400;"> Le nom du compte bancaire : {{ $compte_bank_username }}

                        </h1>
                        <br>
                        <h1 class="head-text" style="font-weight: 400;"> N° Compte : {{ $compte_bank_rib }}

                        </h1>
                        <br>
                        <h1 class="head-text" style="font-weight: 400;"> Nom de Banque : {{ $compte_bank_name}}
                        </h1>

                    </div>
                </th>
                <th style="text-align: left; margin-left: 20px;">
                    <div class=" margin-left">
                        <h1 class="head-text sb-total" style="font-weight: 400; font-size: 18px;"> Total: <span
                                class="px-stl"> {{  number_format($subtotal, 2, '.', ',') }} MAD</span>
                        </h1>
                       @if($remise > 0)
                        <br>
                        <h1 class="head-text sb-total " style="text-align: left; font-weight: 400; font-size: 18px; margin-right: -10px; color: #27ae60">
                            Remise: <span class="px-stl">  -{{  number_format($remise, 2, '.', ',') }} MAD</span>
                        </h1>

                        <br>
                        @endif
                        <br>
                        <h1 class="head-text sb-total" style="font-weight: 400; font-size: 18px; margin-right: -10px">
                            TVA ({{ $tva_percentage }}%): <span class="px-stl">  {{  number_format($tva, 2, '.', ',') }} MAD</span>
                        </h1>
                        <br>
                        <div class="total-border">
                            <h1 class="" style="font-weight: 600; font-size: 23px; line-height: 1;"> Total Final: <span
                                    class="">&nbsp; &nbsp;  {{  number_format($TotalFinal, 2, '.', ',') }} MAD</span>
                            </h1>
                        </div>
                    </div>
                </th>
            </tr>
        </table>
    </div>


@if ($remarque != "")
<div class="remarqe">
    <div class="remarqe-text"><span class="" style="font-size: 13px"> {{ $remarque }}
</div>
@endif

    <br>
    <!-- Footer-->
    <div class="footer">
        <div class="border-info"><span style="font-size: 13px"> PLUS D'INFORMATION</span></div>
        <br>
        <table style="margin-left: auto !important;
        margin-right: auto !important; " dir="ltr" align="center">
            <tr>
                <th style="text-align: center;">


                    <h1 class="head-text" style="font-weight: 400; font-size: 13px; line-height: 1; color:black">
                        ICE: {{ $ice }}
                    </h1>

                </th>
                <th style="text-align: center;">


                    <h1 class="head-text" style="font-weight: 400; font-size: 13px; line-height: 1; color:black">
                        IF: {{ $if }}
                    </h1>

                </th>
                <th style="text-align: center;">


                    <h1 class="head-text" style="font-weight: 400; font-size: 13px; line-height: 1; color:black">
                        TP: {{ $tp}}
                    </h1>


                </th>
                <th style="text-align: center;">


                    <h1 class="head-text" style="font-weight: 400; font-size: 13px; line-height: 1; color:black">
                       Tel: {{ $telephone }}
                    </h1>


                </th>
                <th style="text-align: center;">


                    <h1 class="head-text" style="font-weight: 400; font-size: 13px; line-height: 1; color:black">
                       Email: {{ $b_email }}
                    </h1>


                </th>
            </tr>
        </table>
    </div>
    </div>
    <br>
