<style>
/* #### Generated By: http://www.cufonfonts.com #### */

@import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap');
*{
    font-family: 'Open Sans', sans-serif !important;

    }
    .grid {
    width: 100%;
    display: inline-flex;
    margin-left: auto;
    margin-right: auto;
}
.grid div {
    width: 100%;
}
h1.logo-text {
    font-size: 20px;
    line-height: 0;
    color: #151515;
}
p.logo-slogon {
    font-size: 15px;
    font-weight: 300;
   /* margin-top: -15px;*/
}
h1.head-text {
    font-size: 14px;
    font-weight: 300;
    line-height: 0;
}

body {
    width: 100%;
    text-align: left;

}
table{
    text-align: left;

}

td, th {
  /*border: 1px solid #dddddd;*/
  text-align: left;
  padding: 8px;
}

.border-orange {
    background-color: #ffb100;
    text-align: right;
    color: white;
    height: 40px;
    padding: 0 !important;
    margin-top: 10px;
    margin: 0;
    width: 100%;
}

.og-text {
    position: absolute;
    color: #ffb100;
    background-color: white;
    margin-right: 15%;
    font-size: 50px;
    width: 100%;
    max-width: 200px;
    text-align: center;
    margin-left: auto;
    margin-top: 0;
    margin-bottom: 0;
    padding: 0px !important;
    right: 15px;
    top: 78px;
}
.content-right-td {
    text-align: left;
    display: block;
    margin-left: 25%;
}
.margin-left {
    margin-right: -50px;
}
</style>
<?php
$phonepng = file_get_contents('icons/phone.png');
$phonepng64 = base64_encode($phonepng);
?>
<head>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' >
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700&display=swap" rel="stylesheet">
</head>
<!--div class="top-section grid">
    <div>
        <h1 class="logo-text"> SAAD RIFAI</h1>
        <p class="logo-slogon">Full Stack Developer </p>
    </div>
    <div>
        <h1 class="head-text"> date de la creation</h1>
        <p class="slogon-text"> 02/05/2021 </p>
    </div>
</div-->

<div style="width: 100%;">
<table style="width:100%; height: 100px; padding: 0; margin: 0;" dir="ltr" align="left">
    <tr>
      <th style="">
          <div>
        <h1 class="logo-text"> SAAD RIFAI</h1>
        <p class="logo-slogon">Full Stack Developer </p>
    </div>
      </th>
        <th style="text-align: right;">
            <div class="content-right-td">
            <h1 class="head-text"> date de la creation</h1>
            <p class="slogon-text" style="font-weight: 300;"> 02/05/2021 </p>
        </div>
        </th>
    </tr>
    <tr><td colspan="2"><br></td></tr>
    <tr style=" padding: 0; margin: 0;"> <td colspan="2" class="border-orange"> <div class="og-text"><span class=""> DEVIS </span></div></td> </tr>
  </table>
<br>

  <!-- Infos Devis Section -->
  <table style="width:100%; height: 100px; padding: 0; margin: 0;" dir="ltr" align="left">
    <tr>
        <th style="text-align: left;">
            <div class="">
            <h1 class="head-text" style="font-weight: 400; font-size: 18px;"> Contactez-nous
            </h1>
            <br>
            <h1 class="head-text" style="font-weight: 400;"><span class="icon-text"> <img width="50" src="data:image;base64 ,<?= $phonepng64; ?>" alt="phone"> </span> 06 65 03 34 60
            </h1>
            <br>
            <h1 class="head-text" style="font-weight: 400;"> s.rifai@moqawala.ma
            </h1>
            <br>
            <h1 class="head-text" style="font-weight: 400;"> www.moqawala.ma
            </h1>
        </div>
        </th>
        <th style="text-align: left; margin-left: 20px;">
            <div class=" margin-left">
                <h1 class="head-text" style="font-weight: 400; font-size: 18px;"> Client
                </h1>
                <br>
                <h1 class="head-text" style="font-weight: 400;"> Adil Miftah
                </h1>
                <br>
                <h1 class="head-text" style="font-weight: 400;"> s.rifai@moqawala.ma
                </h1>
                <br>
                <h1 class="head-text" style="font-weight: 400;"> 06 63 35 31 21</h1>                
                <br>
                <h1 class="head-text" style="font-weight: 400;"> Tanger, Maroc</h1>
            </div>
        </th>
    </tr>
  </table>
</div>
  <br>
