 <?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
        <url>
            <loc>{{asset('/')}}</loc>
            <lastmod>2021-12-22</lastmod>
            <changefreq>weekly</changefreq>
            <priority>1.0</priority>
        </url>
        <url>
            <loc>{{asset('/login')}}</loc>
            <lastmod>2021-12-22</lastmod>
            <changefreq>monthly</changefreq>
            <priority>0.8</priority>
        </url>
        <url>
            <loc>{{asset('/register')}}</loc>
            <lastmod>2021-12-22</lastmod>
            <changefreq>monthly</changefreq>
            <priority>0.8</priority>
        </url>
        <url>
            <loc>{{asset('/auto-entrepreneurs')}}</loc>
            <lastmod>2021-12-22</lastmod>
            <changefreq>daily</changefreq>
            <priority>0.8</priority>
        </url>
        <url>
            <loc>{{asset('/orders')}}</loc>
            <lastmod>2021-12-22</lastmod>
            <changefreq>hourly</changefreq>
            <priority>0.8</priority>
        </url>
        <url>
            <loc>https://blog.desky.ma/</loc>
            <lastmod>2021-12-22</lastmod>
            <changefreq>daily</changefreq>
            <priority>0.7</priority>
        </url>
        <url>
            <loc>{{asset('/q&a')}}</loc>
            <lastmod>2021-12-22</lastmod>
            <changefreq>weekly</changefreq>
            <priority>0.6</priority>
        </url>
        <url>
            <loc>{{asset('/help-center')}}</loc>
            <lastmod>2021-12-22</lastmod>
            <changefreq>weekly</changefreq>
            <priority>0.6</priority>
        </url>
        <url>
            <loc>{{asset('/about')}}</loc>
            <lastmod>2021-12-22</lastmod>
            <changefreq>weekly</changefreq>
            <priority>0.5</priority>
        </url>
</urlset>