<option value="1">البيع عن طريق الأنترنت</option>
	<option value="2">البيع عن طريق المراسلة</option>
	<option value="3">النسيج وتحضير الألياف النسيجية والغزل بطريقة تقليدية</option>
	<option value="4">أنشطة تحويل وحفظ الأسماك والقشريات والرخويات</option>
	<option value="5">تجارة أجهزة الاتصالات بالتقسيط</option>
	<option value="6">تجارة أخرى بالتقسيط خارج المتاجر والأكشاك والأسواق</option>
	<option value="7">تجارة أخرى بالتقسيط في الأكشاك والأسواق</option>
	<option value="8">تجارة الأثاث ومعدات الإضاءة وتجهيزات منزلية أخرى بالتقسيط</option>
	<option value="9">تجارة الأجهزة السمعية البصرية بالتقسيط</option>
	<option value="10">تجارة الأجهزة الكهربائية المنزلية بالتقسيط</option>
	<option value="11">تجارة الأحذية ومنتجات من الجلد بالتقسيط</option>
	<option value="12">تجارة الأسماك والقشريات والرخويات بالتقسيط</option>
	<option value="13">تجارة الألعاب واللعب بالتقسيط</option>
	<option value="14">تجارة البصريات وآلات التصوير بالتقسيط</option>
	<option value="15">تجارة الحواسيب والوحدات الملحقة والبرمجيات بالتقسيط</option>
	<option value="16">تجارة الخبز والحلويات والسكريات بالتقسيط</option>
	<option value="17">تجارة الخردوات والصباغة والزجاج بالتقسيط</option>
	<option value="18">تجارة الزرابي والموكيت وأغطية الجدران والأرض بالتقسيط</option>
	<option value="19">تجارة السلع المستعملة بالتقسيط</option>
	<option value="20">تجارة الصحف ومنتجات من الورق بالتقسيط</option>
	<option value="21">تجارة العطور ومواد التجميل بالتقسيط</option>
	<option value="22">تجارة الفواكه والخضر بالتقسيط</option>
	<option value="23">تجارة الكتب بالتقسيط</option>
	<option value="24">تجارة اللحوم ومشتقات اللحوم بالتقسيط</option>
	<option value="25">تجارة المشروبات بالتقسيط</option>
	<option value="26">تجارة الملابس بالتقسيط</option>
	<option value="27">تجارة المنتجات الغذائية بالتقسيط في الأكشاك والأسواق</option>
	<option value="28">تجارة المنسوجات بالتقسيط</option>
	<option value="29">تجارة المنسوجات والملابس والأحذية في الأكشاك والأسواق</option>
	<option value="30">تجارة المواد الغذائية</option>
	<option value="31">تجارة تسجيلات الموسيقى والفيديو بالتقسيط</option>
	<option value="32">تجارة معدات رياضية بالتقسيط</option>
	<option value="33">تحضير وصنع منتجات من الجلد</option>
	<option value="34">تحويل الحبوب</option>
	<option value="35">تحويل اللحوم والدواجن وحفظها بطريقة تقليدية</option>
	<option value="36">تحويل وحفظ الفواكه والخضر</option>
	<option value="37">تفكيك الحطام واسترداد النفايات المفروزة</option>
	<option value="38">صناعات تحويلية أخرى</option>
	<option value="39">صناعة الخبز والحلويات</option>
	<option value="40">صناعة الفراشي والمكانس والمنافض</option>
	<option value="41">صناعة يدوية للأحذية</option>
	<option value="42">صناعة يدوية للزرابي</option>
	<option value="43">صنع الأثاث</option>
	<option value="44">صنع الأطعمة والأطباق المعدة</option>
	<option value="45">صنع الآلات الموسيقية</option>
	<option value="46">صنع التوابل والبهارات</option>
	<option value="47">صنع الزيوت والدهون</option>
	<option value="48">صنع الشكولاتة والحلويات السكرية</option>
	<option value="49">صنع الصباغة والبرنيق والحبر والصمغ</option>
	<option value="50">صنع العجائن الغذائية والكسكس</option>
	<option value="51">صنع الغراء</option>
	<option value="52">صنع المثلجات والصوربي</option>
	<option value="53">صنع المجوهرات المقلدة ومواد مشابهة</option>
	<option value="54">صنع الملابس</option>
	<option value="55">صنع الملونات والصباغ</option>
	<option value="56">صنع حرفي لمنتجات النسيج والملابس التقليدية</option>
	<option value="57">صنع حرفي لمنتجات تقليدية من المعادن والصفائح لحوافر الدواب</option>
	<option value="58">صنع حرفي لمنتجات متنوعة من الخشب والقصب والحلفاء</option>
	<option value="59">صنع منتجات الألبان بما في ذلك الجبن</option>
	<option value="60">صنع منتجات تقليدية من الطين المعد</option>
	<option value="61">صنع منتجات خزفية ومن الطين المعد</option>
	<option value="62">صنع منتجات متنوعة من الخشب والفلين</option>
	<option value="63">صنع منتجات معدنية</option>
	<option value="64">صنع مواد التنظيف</option>
	<option value="65">صنع وتحويل عناصر للبناء</option>
	<option value="66">صياغة وتحويل الزجاج</option>
	<option value="67">نشر ونجر الخشب</option>