@extends('layout.master')
@section('title', 'شروط الاستخدام')

@section('content')
    <div class="head-cbrand position-relative">
        <h1 class="title-page-cbrand text-center  position-absolute top-50 start-50 translate-middle">شروط الاستخدام</h1>
    </div>


    <div class="container">
        <div class="row justify-content-md-center mx-auto w-100" style="max-width: 950px" dir="rtl">
            <!--div class="col-sm col-lg-3">
                <div class="card list-paragraph mt-5 p-3">
                    <h1 class="card-title mb-4 mt-3" style="font-size: 16px">المحتوايات</h1>
                    <nav class="nav flex-column" id="list-content">
                        <a class="nav-link active" aria-current="page" href="#h1">المقدمة</a>
                        <a class="nav-link" href="#h2">الحساب</a>
                        <a class="nav-link" href="#h3">المقاول ذاتي</a>
                        <a class="nav-link" href="#h4">ضمان الحقوق</a>
                        <a class="nav-link" href="#h5">تفعيل الحساب</a>
                      </nav>
                </div>
            </div-->
            <div class="col-sm">
                <div class="  mx-auto mt-5 mb-5 page-text" >

                    <div class="font-Naskh">
                        <h1 dir="rtl" style="line-height:1.38;text-align: right;margin-top:24pt;margin-bottom:6pt;"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">مقدمة:</span></h1>
                        <p dir="rtl" style="line-height:1.38;text-align: right;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">منصة desky عبارة عن وسيط بين المقاولين الذاتيين والعملاء, تقوم منصة desky بالسماح للعملاء أن يضعوا طلباتهم على المنصة قصد الحصول على عروض من المقاولين الذاتيين, أو التواصل مباشر مع المقاول الذاتي من خلال المنصة.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-align: right;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
                        <h1 dir="rtl" style="line-height:1.38;text-align: right;margin-top:24pt;margin-bottom:6pt;"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">مقدم الخدمة</span></h1>
                        <p dir="rtl" style="line-height:1.38;text-align: right;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">منصة desky علامة تجارية تابعة لشركة (NERYOU SARL) التي تم تأسيسها بموجب قوانين المملكة المغربية برأس مال قدره 100,000 درهم بطنجة تحت رقم سجل تجارى 113321 ويقع مقرها الإداري في:</span></p>
                        <p><br></p>
                        <p dir="rtl" style="line-height:1.38;text-align: right;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Technopark Tanger Etage 1 N&deg;T104</span></p>
                        <p><br></p>
                        <p dir="rtl" style="line-height:1.38;text-align: right;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">تكون الجهة المسؤولة عن تقديم الخدمة (NERYOU SARL) والتي تتعاقد معها أنت.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-align: right;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
                        <h1 dir="rtl" style="line-height:1.38;text-align: right;margin-top:24pt;margin-bottom:6pt;"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">علاقتك مع NERYOU</span></h1>
                        <p dir="rtl" style="line-height:1.38;text-align: right;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">تساعد هذه البنود على تحديد العلاقة بينك وبين NERYOU. وبصفة عامة، نمنحك الإذن باستخدام خدماتنا في حال موافقتك على اتباع هذه البنود التي تبيِّن طريقة NERYOU في ممارسة أعمالها. عند ذِكْر &quot;NERYOU أو desky&quot; واستخدام صيغة المتكلم مثل &quot;نحن&quot; و&quot;إننا&quot; و&quot;نا&quot; و&quot;الخاص بنا&quot;، نقصد شركة &nbsp;NERYOU SARL والشركات التابعة لها.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-align: right;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span></p>
                        <h1 dir="rtl" style="line-height:1.38;text-indent: -36pt;text-align: right;margin-top:20pt;margin-bottom:0pt;padding:0pt 36pt 0pt 0pt;"><span style="font-size:6.999999999999999pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp;&nbsp;</span><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1.</span><span style="font-size:6.999999999999999pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"></span><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">الحساب</span></h1>
                        <span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br></span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> أنواع الحسابات</span>
                        <span style="font-size:20pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br></span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">نوفر لك نوعين من الحسابات التي يمكنك انشائها على المنصة وهما:</span>
                        <h1 dir="rtl" style="line-height:1.38;text-indent: -36pt;text-align: right;margin-top:20pt;margin-bottom:0pt;padding:0pt 36pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">حساب عميل:</span></h1>
                        <p dir="rtl" style="line-height:1.38;text-align: right;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">يمكنك هذا الحساب من نشر طلباتك وتلقي العروض عليها والتواصل مع المقاولين الذاتيين داخل المنصة قصد توظيفهم لإنجاز أعمالك وطلباتك.</span></p>
                        <p><br></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -72pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 72pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">حساب مقاول ذاتي:</span></p>
                        <p dir="rtl" style="line-height:1.38;text-align: right;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">يمكنك هذا النوع من الحساب من تقديم عروض على الصفقات والطلبات المعروضة على المنصة وكما يسمح لك بتلقي رسائل خاصة من عملاء محتملين, كما يسمح لك هذا الحساب أيضا بنشر طلباتك في منصة والتواصل مع مقاولين ذاتيين آخرين قصد تنفيذ طلباتك واعمالك.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -72pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 72pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1.2.</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">التسجيل والقبول</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -108pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 108pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1.2.1.</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">حساب عميل:</span></p>
                        <p dir="rtl" style="line-height:1.38;text-align: right;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">يحق لأي شخص راشد انشاء واستخدام حساب &quot;العميل&quot; على منصة desky قصد إنجاز أعماله وطلباته بدون مراجعة مسبقة للحساب.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -108pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 108pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1.2.2.</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">حساب مقاول ذاتي:</span></p>
                        <p dir="rtl" style="line-height:1.38;text-align: right;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">يمكن للأشخاص المسجلين بنظام &quot;المقاول الذاتي&quot; حصراََ انشاء حساب &quot;المقاول الذاتي&quot; في المنصة ويجب تقديم المعلومات والوثائق اللازمة لتفعيل الحساب (بطاقة المقاول الذاتي أو شهادة التسجيل بنظام المقاول الذاتي, بطاقة الهوية أو بطاقة الاقامة أو جواز سفر ساري المفعول), بعد تقديم طلب تفعيل حساب المقاول الذاتي من خلال (الاعدادات &gt; المقاول الذاتي) مع كافة المعلومات والوثائق المطلوبة فسيتم مراجعة طلبك في غضون 48 ساعة كحد أقصى باستثناء ايام العطل الرسمية والرد عليك إما بالقبول أو بالرفض, في حال رفض طلبك سيتم ابلاغك بالأسباب وسيكون بإمكانك تقديم طلب أخر بعد إصلاح الأخطاء السابقة التي أدت الى رفض طلبك السابق الا في حال قد حصلت على رفض نهائي حينها لن تتمكن من تقديم طلبك مجدداََ, &nbsp;وفي حال كنت تعتقد أنه قد تم منعك من تقديم طلب تفعيل حساب المقاول الذاتي عن طريق الخطأ فبإمكانك تقديم طعن على القرار من خلال إرسال رسالة عبر البريد الالكتروني الى (</span><span style="font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><a href="mailto:support@desky.ma">support@desky.ma</a></span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">) أو من خلال إرسال رسالة عبر البريد إلى العنوان التالي (Technoprk Tanger Egt 1 N&deg;T104, NERYOU SARL) تنبيه: يجب أن تتضمن الرسالة رقم الحساب والبريد الإلكتروني ورقم الهاتف وتوضيح لماذا تظن أن هذا القرار قد تم اتخاذه بشكل خاطئ.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-align: right;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">نحتفظ بالحق في قبول طعنك في القرار أو رفضه بناء على شروط الاستخدام الخاصة بنا واللوائح والقوانين والمعمول بها بالمملكة المغربية أو في حال رأينا انك قد تسبب ضررا لشركة NERYOU أو احدى منتجاتها أو مستخدميها.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -72pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 72pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1.3.</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">إدارة الحساب</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -108pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 108pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1.3.1.تعديل وتصحيح المعلومات الشخصية:</span></p>
                        <p dir="rtl" style="line-height:1.38;text-align: right;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">نمنحك الحق الكامل بتعديل وتصحيح معلوماتك الشخصية والتعرض عليها وفقا للقانون 08-09 الخاص بمعالجة المعطيات ذات الطابع الشخصي باستثناء بريدك الالكتروني الذي لايمكن تغييره لأسباب ادارية, في حال كان حسابك موثق وقمت بتغيير اسمك الشخصي أو جنسك أو تاريخ ميلادك فسيتم إزالة توثيق حسابك وسيتعين عليك تقديم طلب جديد لتوثيق حسابك.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -108pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 108pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1.3.2.تعديل وتصحيح المعلومات المهنية:</span></p>
                        <p dir="rtl" style="line-height:1.38;text-align: right;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">لأسباب أمنية وللحفاظ على سلامة وأمان مجتمعنا و مستخدمينا فلا يمكنك تغيير معلوماتك المهنية من خلال إعدادات حسابك بعد تفعيل حسابك &quot;المقاول الذاتي&quot; في حال كان هناك خطأ في بياناتك المهنية أو قد قمت بتغيير نشاطك أو معلوماتك الضريبة فيمكنك تقديم طلب تصحيح المعلومات المهنية من خلال</span>
                            <a href="/help-center" style="font-size:11pt;">&nbsp;الرابط التالي </a></span>
                            <span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;وتقديم كافة وثائق الإثبات اللازمة ( شهادة المقاول الذاتي, وثيقة رسمية من ادارة الضرائب...) سيتم دراسة طلبك في غضون 48 ساعة كحد أقصى باستثناء أيام العطل الرسمية ونحتفظ بالحق في قبول أو رفض طلبك بناءا على تقديرنا وشروط الاستخدام الخاصة بنا واللوائح المعمول بها.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -72pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 72pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1.4.</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">حضر ومراجعة الحساب</span></p>
                        <p><br></p>
                        <p dir="rtl" style="line-height:1.38;text-align: right;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">نحتفظ بالحق في مراجعة أو حظر أي حساب وفقاََ لتقديرنا في حال تبين لنا انه قد خالف سياساتنا وشروط الاستخدام الخاصة بنا أو يسبب الضرر لشركة NERYOU SARL أو احدى منتجاتها أو التأثير على سير واداء خدماتها أو إلحاق الضرر بمستخدميها أو يخالف القوانين واللوائح المعمول بها بالمملكة المغربية &nbsp;بدون سابق انذار وبدون الرجوع الى المستخدم, قد نقوم بطلب وثائق إثبات مثل: بطاقة الهوية أو جواز السفر أو بطاقة الاقامة لإثبات هوية المستخدم قبل السماح له بإكمال استخدام المنصة.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-align: right;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1.4.1.</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">اسباب اغلاق الحسابات</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -18pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 18pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">●</span><span style="font-size:6.999999999999999pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">مخالفة سياسة المحتوى.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -18pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 18pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">●</span><span style="font-size:6.999999999999999pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">تقديم معلومات أو وثائق مزورة أو خاطئة أو استخدام وثائق لشخص أخر.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -18pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 18pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">●</span><span style="font-size:6.999999999999999pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">استخدام حساب المقاول الذاتي من قبل أكثر من شخص سواء كانوا فريقا أم شركة، حيث يسمح فقط لشخص واحد باستخدام الحساب في desky.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -18pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 18pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">●</span><span style="font-size:6.999999999999999pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">انتحال شخصية.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -18pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 18pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">●</span><span style="font-size:6.999999999999999pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">قيام المستخدم (المقاول الذاتي) بانتحال دور الوسيط بحيث عندما يفوز بصفقة يقوم بتوظيف شخص أخر داخل المنصة أو خارجها.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -18pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 18pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">●</span><span style="font-size:6.999999999999999pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">في حال توصلنا بالعديد من البلاغات والشكاوى بخصوص حساب ما فإننا سنقوم بمراجعة الحساب واتخاد إجراء بشأنه.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -18pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 18pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">●</span><span style="font-size:6.999999999999999pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">تسبب المستخدم بضرر لمستخدم آخر داخل المنصة أو لشركة &nbsp;NERYOU SARL &nbsp;أو احدى منتجاتها قد يعرضه الى تعليق أو حظر حسابه بشكل نهائي.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -18pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 18pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">●</span><span style="font-size:6.999999999999999pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">مخالفة سياسة الأمان</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -18pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 18pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">●</span><span style="font-size:6.999999999999999pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">عدم تنفيذ المقاول الذاتي للعمل المطلوب بعد اتفاقه مع العميل واختياره بدون سبب جوهري.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -18pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 18pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">●</span><span style="font-size:6.999999999999999pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">قيام العميل بنشر عدة طلبات بدون إكمالها عند تلقي العروض أو القيام بتزويد المقاول الذاتي بمعلومات خاطئة مثل عنوان اللقاء وعدم الجدية.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -18pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 18pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">●</span><span style="font-size:6.999999999999999pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">الإصرار على التواصل خارج المنصة بدون ضرورة.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -18pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 18pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">●</span><span style="font-size:6.999999999999999pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">طلب من العميل إجراء تحويل بنكي بدون لقاء بين الطرفين.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -18pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 18pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">●</span><span style="font-size:6.999999999999999pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">تقديم المقاول الذاتي على عمل لا يجيده أو انجازه بجودة منخفضة أو قيام العميل برفع شكوى ضد المقاول الذاتي</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -18pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 18pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">●</span><span style="font-size:6.999999999999999pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">وجود دعاوى قانونية في حق المستخدم بسبب النصب والاحتيال أو العنصرية أو ممارسة نشاط غير قانوني أو اي قضية تتعلق بسوء استخدام منتجات NERYOU فسيتم تعليق الحساب حتى يصدر قرار السلطات المختصة بشأن القضية أو الدعوى المرفوعة ضد المستخدم عندها سنتخذ إجراء بشأن حسابك اما اعادة تنشيطه أو حظره نهائياََ.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -18pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 18pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">●</span><span style="font-size:6.999999999999999pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">رفع صورة شخصية للحساب ليست بصورة مالك الحساب نفسه، من ضمن ذلك استخدام صور شخصيات عامة.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -18pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 18pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">●</span><span style="font-size:6.999999999999999pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">بيع الحساب، وعند اكتشاف عملية بيع أي حساب يتم إيقافه مباشرة ولا يمكن لأي طرف الاستفادة منه.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-indent: -18pt;text-align: right;margin-top:12pt;margin-bottom:12pt;padding:0pt 18pt 0pt 0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">●</span><span style="font-size:6.999999999999999pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">قيام المقاول الذاتي بإنشاء أكثر من حساب.</span></p>
                        <p dir="rtl" style="line-height:1.38;text-align: right;margin-top:12pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">نقوم بتعديل شروط الاستخدام من حين لأخر من أجل ضمان أمن وسلامة مستخدمينا ومنتجاتنا</span>
                        <br>
                        <br>
                        <br>
                        <span> أخر تعديل: 22/12/2021</span>
                        </p>
                        <p><br></p>
                        <p><br></p>

                    </div>





                </div>
            </div>
        </div>
      
    </div>
@stop
